name: Tests (Bun)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --ignore-scripts
      - name: Run formatter, linter, import sorter
        run: bun ci
      - name: Build knip
        run: bun run build
        working-directory: packages/knip
      - name: Run knip
        run: ./packages/knip/bin/knip-bun.js
      - name: Run knip (production/strict)
        run: ./packages/knip/bin/knip-bun.js --production --strict
      - name: Test knip
        run: bun run test:bun
        working-directory: packages/knip
